// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © jdehorty
//@version=5
strategy("DZ Backtest Adapter",
              shorttitle = "DZ-backtest",
              overlay = true,
              precision = 2,
              pyramiding = 0,
              initial_capital = 10000,
              currency = currency.NONE,
              default_qty_type = strategy.percent_of_equity,
              default_qty_value = 100,
              commission_type = "percent",
              commission_value = 0.06)

var start = timestamp("1 Jan 2020")

i_use_date_filter = input.bool  (true,  title="Begin Backtest at Start Date", group="Backtest Time Period")
i_backtest_start  = input.time  (start, title="Start Date",                   group="Backtest Time Period")

i_pivot_left      = input.int   (15,    title="Pivot Left Bars",              group="General Settings")
i_pivot_right     = input.int   (15,    title="Pivot Right Bars",             group="General Settings")
i_entry_src       = input.source(close, title="Source",                       group="General Settings")
i_risk_reward     = input.float (2.0,   title="Risk Reward Ratio",            group="General Settings")

// NOTE(DZ): Currently this is not allowed
// https://www.tradingview.com/support/solutions/43000474048-how-do-i-apply-an-indicator-or-strategy-to-another-indicator/
// i_long_stop_src   = input.source(open,  title="Long Stop loss source",        group="General Settings")
// i_short_stop_src  = input.source(open,  title="Short Stop loss source",       group="General Settings")
// i_long_tp_src     = input.source(open,  title="Long Take profit source",      group="General Settings")
// i_short_tp_src    = input.source(open,  title="Short Take profit source",     group="General Settings")

// Stop loss calculations - pivots
resistance = fixnan(ta.pivothigh(i_pivot_left, i_pivot_right)[1])
support  = fixnan(ta.pivotlow(i_pivot_left, i_pivot_right)[1])

in_trade_window = not i_use_date_filter or time >= i_backtest_start

start_long = strategy.position_size == 0 and i_entry_src == 1 and in_trade_window
stop_long = strategy.position_size > 0 and i_entry_src == 2
start_short = strategy.position_size == 0 and i_entry_src == -1 and in_trade_window
stop_short = strategy.position_size < 0 and i_entry_src == -2

bgcolor(color = color.new(start_long ? color.green : stop_long ?  color.aqua : start_short ?  color.red : stop_short ?  color.purple : na, 50))
plot(resistance, color=ta.change(resistance) ? na : #FF0000, linewidth=3, offset=-(i_pivot_right+1), title="Resistance")
plot(support, color=ta.change(support) ? na : #233dee, linewidth=3, offset=-(i_pivot_right+1), title="Support")

if start_long
    strategy.entry("🟢", strategy.long)

if stop_long
    strategy.close_all(comment="🛑")

if start_short
    strategy.entry("🟣", strategy.short)

if stop_short
    strategy.close_all(comment="🛑")
