//© zyqxd
//@version=5

strategy(title = "Supertrend strategy",
     shorttitle = "ST-strat",
     overlay = true,
     precision = 2,
     pyramiding = 0,
     initial_capital = 10000,
     default_qty_type = strategy.percent_of_equity,
     default_qty_value = 100,
     commission_type = "percent",
     commission_value = 0.06)

// Strategy
i_strat_tp1     = input.float     (2,                  title='TP lv1 %',              group="Strategy", step=0.1) / 100
i_strat_tp2     = input.float     (8,                  title='TP lv2 %',              group="Strategy", step=0.1) / 100
i_strat_tp3     = input.float     (20,                 title='TP lv3 %',              group="Strategy", step=0.1) / 100
i_strat_sl      = input.float     (2,                  title='Stop lv %',             group="Strategy", step=0.1) / 100

// Supertrend
i_periods       = input.int       (14,                 title="Supertrend period",     group="Supertrend")
i_multiplier    = input.float     (3.0,                title="Supertrend Factor",     group="Supertrend", step=0.1)
i_fast_tf       = input.timeframe ("60",               title="Fast Timeframe",        group="Supertrend")
i_slow_tf       = input.timeframe ("D",                title="Slow Timeframe",        group="Supertrend")
i_show_signals  = input.bool      (true,               title="Show signals",          group="Supertrend")


[trend, direction] = ta.supertrend(i_multiplier, i_periods)

if ta.change(direction, 1) < 0
    strategy.entry("long", strategy.long)

if ta.change(direction, 1) > 0
    strategy.entry("short", strategy.short)

plot(trend, color=color.red)
plot(direction, color=color.green)

// pa = plot(ohlc4, color = color.new(color.white, 100))
// // Plot for slow supertrend
// [upA, dnA, trendA, signalA] = security(syminfo.tickerid, slowTf, trendInfo(periods, multiplier))
// aUpPlot = plot(trendA == 1 or showInverse ? upA : na, color = color.green)
// aDnPlot = plot(trendA == -1 or showInverse ? dnA : na, color = color.red)
// fill(pa, aUpPlot, color = color.new(color.green, trendA == 1 ? 90 : 99))
// fill(pa, aDnPlot, color = color.new(color.red, trendA == -1 ? 90 : 99))

// // Plot for fast supertrend
// [upB, dnB, trendB, signalB] = security(syminfo.tickerid, fastTf, trendInfo(periods, multiplier))
// bUpPlot = plot(trendB == 1 or showInverse ? upB : na, style = plot.style_linebr, color = color.teal)
// bDnPlot = plot(trendB == -1 or showInverse ? dnB : na, style = plot.style_linebr, color = color.purple)

// longCondition = trendA == 1 and low <= upB
// shortCondition = trendA == -1 and high >= dnB
// trendingLongCondition = signalB and trendB == 1 and trendA == 1
// trendingShortCondition = signalB and trendB == -1 and trendA == -1

// // Plot signals for fast supertrend
// plotshape(showSignals and longCondition ? upB : na,
//           text = "Buy",
//           location = location.absolute,
//           style = shape.labelup,
//           size = size.tiny,
//           color = color.teal,
//           textcolor = color.white)

// plotshape(showSignals and shortCondition ? dnB : na,
//           text = "Sell",
//           location = location.absolute,
//           style = shape.labeldown,
//           size = size.tiny,
//           color = color.purple,
//           textcolor = color.white)

// if isTrending
//     if trendingLongCondition
//         strategy.entry("long", strategy.long, limit=upB, comment="🟢")

//     if trendingShortCondition
//         strategy.entry("short", strategy.short, limit=dnB, comment="🔴")

//     strategy.exit("⭐️", "long", qty_percent=33, limit=strategy.position_avg_price * (1 + strat_tp1))
//     strategy.exit("⭐️⭐️", "long", qty_percent=33, limit=strategy.position_avg_price * (1 + strat_tp2))
//     strategy.exit("⭐️⭐️⭐️", "long", qty_percent=33, limit=strategy.position_avg_price * (1 + strat_tp3))

//     strategy.exit("⭐️", "short", qty_percent=33, limit=strategy.position_avg_price * (1 - strat_tp1))
//     strategy.exit("⭐️⭐️", "short", qty_percent=33, limit=strategy.position_avg_price * (1 - strat_tp2))
//     strategy.exit("⭐️⭐️⭐️", "short", qty_percent=33, limit=strategy.position_avg_price * (1 - strat_tp3))

//     strategy.exit("🎯", "long", stop=strategy.position_avg_price * (1 - strat_sl))
//     strategy.exit("🎯", "short", stop=strategy.position_avg_price * (1 + strat_sl))
// else
//     if longCondition
//         strategy.entry("long", strategy.long, limit=upB, when=strategy.position_size <= 0, comment="🟢")

//     if shortCondition
//         strategy.entry("short", strategy.short, limit=dnB, when=strategy.position_size <= 0, comment="🔴")

//     strategy.exit("🎯", "long", limit=dnB, stop=strategy.position_avg_price * (1 - strat_sl))
//     strategy.exit("🎯", "short", limit=upB, stop=strategy.position_avg_price * (1 + strat_sl))

// plot(strategy.position_avg_price * (1 - strat_sl), color=color.red)
// plot(strategy.position_avg_price * (1 + strat_sl), color=color.green)
